name = "ccg-listing-evaluator"
main = "src/index.ts"
compatibility_date = "2026-01-29"

# Fill these before deploying.
account_id = "29c0b8377a7d6c5259e8b5cc977e2aaf"
route = "https://www.coalcreekguitars.com/api/*"

[vars]
APIFY_FACEBOOK_ACTOR = "apify/facebook-marketplace-scraper"
APIFY_CRAIGSLIST_ACTOR = "ivanvs/craigslist-scraper"
SITE_BASE_URL = "https://www.coalcreekguitars.com"
MAX_IMAGES = "10"
RADAR_FB_SEARCH_URL = "https://www.facebook.com/marketplace/103985342969890/search?sortBy=creation_time_descend&query=guitar&exact=false"
RADAR_CL_SEARCH_URL = "https://denver.craigslist.org/search/msa?postal=80113&query=guitar&search_distance=20&sort=date"
RADAR_KEYWORDS = "guitar"
AIRTABLE_SEARCH_TABLE = "SearchResults"
RADAR_EMAIL_TO = "davidhopper55@gmail.com"
RADAR_EMAIL_FROM = "david@coalcreekguitars.com"

[triggers]
crons = ["*/5 * * * *"]

[[kv_namespaces]]
binding = "LISTING_JOBS"
id = "b5bb36e9ff1248fd92dd79026b5e784c"
preview_id = "14042ee35da9481fbf659608d39b079e"
